
import time
import os
os.system("pip install colorama")
from colorama import *
init()





def autoopen():
    os.system("clear")
    os.system("chmod +x pass_ish.py")
    print(" <------------WIN!!!------------>")
    print("")
    print("")
    print("")
    print("  Файл успешно создан!")
    print("  Для того чтобы сделать")
    print("  Полностью работоспособную")
    print("  Утилиту её нужно прописать")
    print("  В автозагрузку хотите ли вы")
    print("  Сделать это автоматически?!")
    print( Fore.RED )
    print("")
    print("")
    print( Fore.GREEN )
    print("")
    print("  Если да то напишите - у")
    print("  Если нет то напишите - n")
    print("")
    auto_yn = input(" [y/n]: ")
    if auto_yn == "y":
        os.system("clear")
        print("Выбран авто. режим!")
        print("Ожидайте...")
        time.sleep(6)
        save = open("/data/data/com.termux/files/usr/etc/bash.bashrc", 'r')
        save2 = open("/data/data/com.termux/files/usr/etc/savebash.bashrc", 'w')
        save2.close()
        save2 = open("/data/data/com.termux/files/usr/etc/savebash.bashrc", 'a+')
        save2.write(save.read())
        save.close()
        save2.close()
        f1 = open("/data/data/com.termux/files/usr/etc/bash.bashrc", 'w')
        f1.close()
        f1 = open("/data/data/com.termux/files/usr/etc/bash.bashrc", 'a')
        f2 = open("/data/data/com.termux/files/usr/etc/savebash.bashrc", 'r')
        f1.write("python3 ~/pass_ish/pass_ish.py" + "\n\n" + f2.read())
        f1.close()
        f2.close()
        os.system("rm /data/data/com.termux/files/usr/etc/savebash.bashrc")
        os.system("clear")
        print("             WIN")
        print("")
        print("")
        print("Спасибо за ожидание!")
        print("")
        print("         |Ishihara|")
        print("")
        time.sleep(4)
        print("[Enter] - Продолжить")
        input("")
        os.system("clear")
        print("             WIN")
        print("")
        print("Все готово теперь перезапустим")
        print("Термукс")
        print("")
        print("")
        print("Oжидайте...")
        time.sleep(10)
        os.system('killall -9 com.termux')
        exit
        
        
    elif auto_yn == "n":
        os.system("clear")
        print( Fore.RED )
        print("Вы отказались от авто. режима!")
        print("Чтобы вернуться и выбрать")
        print("Авто. режим  напишите - 1")
        print("")
        print( Fore.GREEN )
        print("Если вы не хотите возвращаться")
        print("Нажмите [Enter]")
        print("")
        deic = input("[] ")
        if deic == "1":
            autoopen()
        else:
            os.system("clear")
            print("       Подсказка")
            print("Дальше вы должны сами ")
            print("Прописать файл pass_ish")
            print("В автозагрузку!!!")
            print("")
            print("             |Ishihara|")
            print("")
            print("[Enter] - Чтобы выйти!")
            input("")
            time.sleep(2)
            exit
        
        
        
        
    










def installer():
    os.system("clear")
    print( Back.BLACK )
    print( Fore.GREEN )
    print("")
    print("|Script by Ishihara|")
    print("")
    print("<-----------Welcome-to-installer----------->")
    print("                                    Vr-2.0")
    print("\n \n ")
    print("Перед началом убедитесь!")
    print("Выдайте файлу installer_ish.py")
    print("Права командой chmod +x")
    print("Пример: chmod +x installer_ish.py")
    print("")
    print("")
    print("[Enter] - Чтобы продолжить!")
    
    input("")
    os.system("clear")

    print("Пожалуйста запомните все \nданные что вы вводите!!!")
    print("")
    print("Ожидайте...")
    time.sleep(5)
    os.system("clear")
    print("Хотите ли вы видеть простенький")
    print("Приветственный экран?")
    print("")
    print("Если хотите то введите - y")
    print("Если не хотите то - n")
    print("")
    ecr = input("[y/n]: ")
    os.system("clear")
    print("Введите ник который будет использован!")
    print("")
    username = input("Username: ")
    os.system("clear")
    print("Введите пароль который будет использован!")
    print("")
    password = input("Password: ")
    os.system("clear")
    print( Fore.RED )
    print("Сейчас у вас запросят еще один пароль \nКоторый будет использован")
    print("В том случае если вам нужно будет")
    print("Экстренно удалить папки(или другие файлы)")
    print("Какие именно файлы вы хотите удалить")
    print("Вы выберите чуть позже")
    print("")
    print("Ожидайте...")
    time.sleep(10)
    print( Fore.GREEN )
    print("")
    print("Нажмите [Enter] чтобы продолжить!")
    input("")
    os.system("clear")
    print("Введите пароль для удаления файлов!")
    print("Или не вводите ничего если не хотите!")
    print("Данную функцию!")
    print("")
    passworderror = input("EX-Password: ")
    os.system("clear")
    print( Fore.RED )
    print("Осталось заполнить директории файлов \nкоторые вы хотите удалить")
    print("Ожидайте...")
    time.sleep(4)
    print( Fore.YELLOW )
    print("Введите название файлов \nКак показано в примере!")
    print("")
    print("Пример: Если у меня в домашней \nДиректории есть папка")
    print("test")
    print("И я хочу чтобы при вводе пароля " + passworderror + "\nОна удалилась то я пишу так: ")
    print("test")
    print("")
    print("Ожидайте...")
    time.sleep(8)
    print("Нажмите [Enter] чтобы продолжить!")
    input("")
    os.system("clear")
    print("У вас есть возможность при вводе пароля:")
    print(passworderror)
    print("Удалить 4 файла(Папки)")
    print("Из домашней директории!")
    print("")
    print("[Enter] - Чтобы продолжить!")
    input("")
    os.system("clear")
    print("Усли у вас больше 4 файлов(папок):")
    print("Рекомендуется поместить все файлы(папки)")
    print("В одну и прописать ее название")
    print("Таким образом удалится выбранная")
    print("Папка со всеми вложеными в нее файлами!")
    print("Вы можете сделать это прямо сейчас!")
    print("Не закрывая эту программу откройте 2")
    print("Сессию и работайте над этим в ней")
    print("После чего вернитесь и нажмите:")
    print("")
    print("[Enter] - Чтобы продолжить!")
    input("")
    os.system("clear")
    print("Если же вы наоборот \nНе хотите ничего удалять \nИли у вас меньше 4 файлов(папок)")
    print("Введите названия того что хотите удалить")
    print("А после просто нажимайте [Enter]")
    print("Не вводя никаких символов даже пробел!!!")
    print("Если не хотите удалять вообще ничего")
    print("То не вводите ничего а просто нажимайте")
    print("на [Enter]")
    print("")
    print("[Enter] - Чтобы продолжить!")
    input("")
    os.system("clear")
    print( Fore.GREEN )
    print("В данный момент у вас в домашней")
    print("Директории находятса эти файлы")
    os.system("ls ~/")
    print("")
    print("")
    print( Fore.GREEN )
    print("Выберите 1 файл который")
    print("Удалится при вводе пароля: ")
    print(passworderror)
    delfile1 = input("Введите название: ")
    os.system("clear")
    print( Fore.GREEN )
    print("В данный момент у вас в домашней")
    print("Директории находятса эти файлы")
    os.system("ls ~/")
    print("")
    print( Fore.GREEN )
    print("")
    print("Выберите 2 файл который")
    print("Удалится при вводе пароля: ")
    print(passworderror)
    delfile2 = input("Введите название: ")
    os.system("clear")
    print( Fore.GREEN )
    print("В данный момент у вас в домашней")
    print("Директории находятса эти файлы")
    os.system("ls ~/")
    print("")
    print("")
    print( Fore.GREEN )
    print("Выберите 3 файл который")
    print("Удалится при вводе пароля: ")
    print(passworderror)
    delfile3 = input("Введите название: ")
    os.system("clear")
    print( Fore.GREEN )
    print("В данный момент у вас в домашней")
    print("Директории находятса эти файлы")
    os.system("ls ~/")
    print("")
    print("")
    print( Fore.GREEN )
    print("Выберите 4 файл который")
    print("Удалится при вводе пароля: ")
    print(passworderror)
    delfile4 = input("Введите название: ")
    os.system("clear")
    print("")
    print("         Спасибо за ожидание!!!")
    print("")
    print("")
    print("")
    print("")
    print("В данный момент скрипт записывает")
    print("Все данные пожалуйста подождите")
    print("И не выключайте программу!")
    print("")
    print("                      |Ishihara|")
    time.sleep(9)

    f = open('pass_ish.py', 'w')
    f.write("from colorama import *" + "\n" + "import time" + "\n" + "import os" + "\n \n" + "init()")
    f.close()
    f = open('pass_ish.py', 'a+')
    f.write("\n" * 10 + "def home():" + "\n" + "    os.system(\"clear\")")
    if ecr == "y":
        f.write("\n" + "    print( Back.BLACK )" + "\n" + "    print( Fore.GREEN )" + "\n" + "    print(\"    <-------------Welcome------------->\")" + "\n" + "    print(\"\")" + "\n" + "    print(\"                            [root]\")")
        f.write("\n" + "    print(\"                            [" + username + "]\")")
        f.write("\n" + "    print(\"\")" + "\n" + "    print(\"\")" + "\n" + "    print(\"\")" + "\n" + "    print(\"\")")
    f.write("\n \n" + "    exit()")
    f.write("\n \n" + "def passerror():" + "\n" )
    if not delfile1 == "":
        f.write("\n" + "    os.system(\"rm -rf mydir ~/" + delfile1 + "\")")
    if not delfile2 == "":
        f.write("\n" + "    os.system(\"rm -rf mydir ~/" + delfile2 + "\")")
    if not delfile3 == "":
        f.write("\n" + "    os.system(\"rm -rf mydir ~/" + delfile3 + "\")")
    if not delfile4 == "":
        f.write("\n" + "    os.system(\"rm -rf mydir ~/" + delfile4 + "\")")
    f.write("\n")
    f.write("    home()")
    f.write("\n \n \n \n \n" + "def passwords():")
    f.write("\n" + "    thunder = True" + "\n" + "    if thunder == True:" + "\n" + "        print(\"\")" + "\n" + "        os.system(\"clear\")" + "\n" + "        print( Back.BLACK )" + "\n" + "        print( Fore.RED )")
    f.write("\n" + "        print(\"|script by Ishihara|\")" + "\n \n \n \n" + "        print(\"\")" + "\n" + "        print(\"    <-------------Welcome------------->\")" + "\n" + "        print(\"\")" + "\n" + "        print(\"\")" + "\n" + "        print(\"\")" + "\n" + "        print(\"                                [jerk]\")" + "\n" + "        time.sleep(1)" + "\n" + "\n" + "        print(\"\")" + "\n" + "        print(\"\")" +  "\n" + "        print(\"\")" + "\n" + "        print(\"\")" + "\n" + "        try:")
    f.write("\n" + "            x = \"" + password + "\"" "\n" + "            y = \"" + username + "\"")
    f.write("\n" + "            username = input(\"Username: \")" + "\n" + "            password = input(\"Password: \")")
    f.write("\n" + "            if password == x and username == y:" + "\n" + "                thunder = False" + "\n" + "                home()")
    if not passworderror == "":
        f.write("\n" + "            elif password == \"" + passworderror + "\":" + "\n" + "                thunder = False" + "\n" * 3 + "                passerror()")
    f.write("\n" + "            elif password == \"12\":")
    f.write("\n" + "                try:" + "\n" + "                    os.system(\"clear\")" + "\n" + "                    print(\"|Error-404|\" * 404)")
    f.write("\n" + "                    time.sleep(3)")
    f.write("\n" + "                    os.system(\"clear\")")
    f.write("\n" + "                    print(\"             Hello!\")")
    f.write("\n" + "                    print(\"\")")
    f.write("\n" + "                    print(\"\")")
    f.write("\n" + "                    print(\"\")")
    f.write("\n" + "                    print(\"\")")
    f.write("\n" + "                    time.sleep(8)")
    f.write("\n" + "                    print(\"\")" + "\n" + "                    print(\"Author: Ishihara\")")
    f.write("\n" + "                    print(\"\")")
    f.write("\n" + "                    print(\"\")")
    f.write("\n" + "                    passwords()")
    f.write("\n" + "                except Exception:")
    f.write("\n" + "                    os.system('killall -9 com.termux')")
    f.write("\n" + "                    print(\"In Vain...\")")
    f.write(" ")
    f.write(" ")
    f.write("\n" + "                except KeyboardInterrupt:")
    f.write("\n" + "                    os.system('killall -9 com.termux')")
    f.write("\n" + "                    print(\"In Vain...\")")
    f.write(" ")
    f.write(" ")
    f.write(" ")
    f.write("\n" + "            else:")
    f.write("\n" + "                print(\"\")")
    f.write("\n" + "                print(\"\")")
    f.write("\n" + "                print(\"\")")
    f.write("\n" + "                print(\"\")")
    f.write("\n" + "                print(\"\")")
    f.write("\n" + "                print(\"No...\")")
    f.write("\n" * 3 + "            time.sleep(2)")
    f.write("\n" * 3 + "            passwords()")
    f.write("\n" + "        except Exception:")
    f.write("\n" + "            os.system('killall -9 com.termux')")
    f.write("\n" + "            print(\"In Vain...\")")
    f.write("\n" + "        except KeyboardInterrupt:")
    f.write("\n" + "            os.system('killall -9 com.termux')")
    f.write("\n" + "            print(\"In Vain...\")")
    f.write("\n" + "passwords()")
    f.close()
    autoopen()
    
    
    
    
installer()
